## read numpy basics

import numpy as np

array from list

In [6]:
import numpy as np

In [7]:
arr_1d=np.array([1,2,3,4,5])
print("1Darray is",arr_1d)

1Darray is [1 2 3 4 5]


## list vs numpy array

In [8]:
py_list=[1,2,3]
print("the mul of list is\n",(py_list*2)) #HERE 2 is normally a number.

arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("the mul of list is\n",arr*2)    #here in array(matrices)2 is called scaler .scaler use for matrices


the mul of list is
 [1, 2, 3, 1, 2, 3]
the mul of list is
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## code to check the time efficiency

In [9]:
# here this file(code) shows that num.py is more time sufficient than list 

import time 
start=time.time()
py_list=[i*2 for i in range(100)]
   # py_list=[i*2 ]
print("\nthe time is:",time.time()-start )

start=time.time()
np_arr= np.arange(100)*2
print("\n the time is :",time.time()-start)


the time is: 0.00039267539978027344

 the time is : 0.0005364418029785156


## creating array from scratch

In [3]:
import numpy as np
zeros=np.zeros((3,2))
print(zeros)   # zeros use for create a matrix which all element 0


ones=np.ones((2,2))
print(ones)
print(ones*2)   # ones use for create a matrix which all element 1

full=np.full((2,2),7)
print(full)     # full use for create a matrix which all element what
                # we want by a number write after braces

random=np.random.random((2,2))
print(random)



sequence=np.arange(0,10)
print(sequence)

s=np.arange(1,15)
print(s)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]
[[7 7]
 [7 7]]
[[0.272907   0.62199591]
 [0.55624754 0.72760155]]
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## vector , marix ,tensor

In [5]:
vector=np.array([1,2,3])
print(vector)

matrix=np.array([[1,2,3],
                [4,5,6]])
print(matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]], 
                 [[9,8],[4,6]]])
print(tensor)

d=(tensor.ndim)
print(d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 8]
  [4 6]]]
3


### array properties

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("shape of array:",arr.shape)
print("dimention of array:",arr.ndim)
print("size of array:",arr.size)
print("datatype of array:",arr.dtype)


shape of array: (3, 3)
dimention of array: 2
size of array: 9
datatype of array: int64


### Array reshaping

In [7]:
arr=np.arange(1,5)
print(arr)          #flat array

reshaped_arr=arr.reshape((2,2))
print(reshaped_arr)                # reshaped array of arr
  
flat_arr=reshaped_arr.flatten()    # flat array of reshaped arr 
print(flat_arr)


transpose_arr=reshaped_arr.T
print(transpose_arr)              # it use for transpose the array 
                                  # it make row column and column to row


         




[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[[1 3]
 [2 4]]
