#### numpy array oprations

In [3]:
import numpy as np

In [ ]:
# slicing in 1darray
arr=np.array([1,2,3,4,5,6,7,8])

print("basic slicing",arr[1:7])
print("step slicing",arr[1:7:2])
print("reverse slicing",arr[-5])


basic slicing [2 3 4 5 6 7]
step slicing [2 4 6]
reverse slicing [3]


In [6]:
# slicing in 2darray
arr_2d=np.array([[1,2,3],      
                 [4,5,6],
                 [7,8,9]])
print(" specific element:",arr_2d[0,0])
 # note = here in python the first row and column is called zeroth row
 # [1,2,3] is zeroth row and 1 4 7 is zeroth column


print(" entire row",arr_2d[1])
print(" entire column",arr_2d[:,2])




 specific element: 1
 entire row [4 5 6]
 entire column [3 6 9]


## SHORTING


In [ ]:
undefined_arr=np.array([1,3,4,1,2,6,8,7])
sorted=np.sort(undefined_arr)
print(sorted)

[1 1 2 3 4 6 7 8]


# for 2d array

In [ ]:
unsorted_array=np.array([[2,1],[3,1],[2,3],[4,1]])
print(np.sort(unsorted_array,axis=1))    #1 for lowest  to greatest


unsorted_array=np.array([[2,1],[3,1],[2,3],[4,1]])
print(np.sort(unsorted_array,axis=0))    # 0 for great to lower

[[1 2]
 [1 3]
 [2 3]
 [1 4]]
[[2 1]
 [2 1]
 [3 1]
 [4 3]]


## filter

In [ ]:
import numpy as np
numbers=np.array([1,2,3,4,5,6,6,7,10])
even_numbers=numbers[numbers%2==0]
print(even_numbers)

[ 2  4  6  6 10]


## Filter with mask

In [ ]:
import numpy as np
numbers=np.array([1,2,3,4,5,6,6,7,10])
mask = numbers < 5
print(mask)
print(numbers[mask])

[ True  True  True  True False False False False False]
[1 2 3 4]


## fancy indexing vs num.py where()

In [ ]:
import numpy as np
numbers=np.array([1,2,3,4,5,6,6,7,10])
indixes=[0,2,4]
print(numbers[indixes])

where_result=np.where(numbers < 5)
print(where_result)
print(numbers[where_result])

condition_array=np.where(numbers>=5,"true","false")
print(condition_array)                # it returns the value which we want by the condition

[1 3 5]
(array([0, 1, 2, 3]),)
[1 2 3 4]
['false' 'false' 'false' 'false' 'true' 'true' 'true' 'true' 'true']


## Adding and removing data 

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined_arr=np.concatenate((arr1,arr2))
print(combined_arr)


[1 2 3 4 5 6]


## array compatibility

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,4])
arr3=np.array([4,9,8])

print("compalibiliti shapes",arr1.shape==arr2.shape==arr3.shape)

arr1=np.array([1,2,3])
arr2=np.array([4,5,9,4])
arr3=np.array([4,9,8])

print("compalibiliti shapes",arr1.shape==arr2.shape==arr3.shape)

compalibiliti shapes True
compalibiliti shapes False


In [ ]:
# for adding a row 
matrix=np.array([[1,2],[3,4]])
new_row=np.array([5,6])

new_matrix=np.vstack((matrix,new_row))
print(matrix)
print(":",new_matrix)


# for adding a column
matrix=np.array([[1,2],[3,4]])
new_col=np.array([[7],[8]])

new_matrix=np.hstack((matrix,new_col))
print(":",new_matrix)






[[1 2]
 [3 4]]
: [[1 2]
 [3 4]
 [5 6]]
: [[1 2 7]
 [3 4 8]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
deleted=np.delete(arr,2)
print(deleted)           # here delete function delete the value 
                         # which store at that index ,here 3 is stored at index 2 


[1 2 4 5 6]


## practise adding row and column

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
new_row=np.array([[7,8,9]])
matrix=np.vstack((arr,new_row))
print(matrix)

new_col=np.array([[4],[2]])
matrix2=np.hstack((arr,new_col))
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [4 5 6 2]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4 5 6 7 8]
