In [26]:
import numpy as np
import matplotlib as plt


## save arrays as a file 

In [6]:
array1=np.array([1,2,3,4])
array2=np.random.rand(3,3)
array3=np.zeros([3,3])

In [ ]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

In [ ]:
loaded_array1=np.load('array1.npy')
print((loaded_array1)*2)
print((loaded_array1)/2)
print((loaded_array1)+5)
print((loaded_array1)-2)
# we do more operations with loaded array.

[2 4 6 8]
[0.5 1.  1.5 2. ]
[6 7 8 9]
[-1  0  1  2]


In [34]:
import numpy as np
import matplotlib as plt

try:
    logo=np.load('h.k.png')
    #display
    plt.figure(figsize=(10, 5))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Numpy Logo")
    plt.grid(False)

    
except FileNotFoundError:
    print("numpy logo file not found")

numpy logo file not found


##